esphome:
  name: "sensorco2"
  platform: ESP32
  board: esp32doit-devkit-v1
  includes:
    - co2_custom_sensor/co2_sensor_gsk.h
    - co2_custom_sensor/CO2Sensor.h
    - co2_custom_sensor/CO2Sensor.cpp

wifi:
  ssid: "UYAMAK"
  password: "DJS5Kn4PUK"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "sensorco2 Fallback Hotspot"
    password: "Ghe4yHB9Dt1I"

logger:

ota:

api:

web_server:
  port: 80
  auth:
    username: HelloUser
    password: HelloPass


    
sensor:
  - platform: custom
    lambda: |-
      auto my_sensor = new MyCustomSensor2();
      App.register_component(my_sensor);
      return {my_sensor};

    sensors:
      name: "CO2 sensor"