esphome:
  name: "1605931940623"
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: "Repeater"
  password: "3C04610F5E84"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "1605931940622 Fallback Hotspot"
    password: "Ghe4yHB9Dt1I"

logger:

ota:

api:

web_server:
  port: 80
  auth:
    username: HelloUser
    password: HelloPass



#For more information how to get the address ... please look https://esphome.io/components/sensor/dallas.html

# Example configuration entry
dallas:
  - pin: GPIO4

# Individual sensors
#sensor:
#  - platform: dallas
#    address: 0xC60217C11E95FF28
#    name: "Living Room Temperature"

#148.212.10.49
