esphome:
  name: "1605931940622"
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: "UYAMAK"
  password: "DJS5Kn4PUK"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "1605931940622 Fallback Hotspot"
    password: "Ghe4yHB9Dt1I"

logger:

ota:

api:

web_server:
  port: 80
  auth:
    username: HelloUser
    password: HelloPass

sensor:
  - platform: dht
    pin: GPIO2
    temperature:
      name: "Bed Temperature"
    humidity:
      name: "Bed Humidity"
    update_interval: 60s    
    
  - platform: custom
    lambda: |-
      auto my_sensor = new MyCustomSensor();
      App.register_component(my_sensor);
      return {my_sensor};

    sensors:
      name: "My Custom Sensor"